#!/bin/bash

run_train_x_classifier.sh amending_agreement
run_train_x_classifier.sh arbitration
run_train_x_classifier.sh assign
run_train_x_classifier.sh change_control
run_train_x_classifier.sh choiceoflaw
run_train_x_classifier.sh confidentiality
run_train_x_classifier.sh date
run_train_x_classifier.sh equitable_relief
run_train_x_classifier.sh events_default
run_train_x_classifier.sh exclusivity
run_train_x_classifier.sh indemnify
run_train_x_classifier.sh insurance
run_train_x_classifier.sh jurisdiction
run_train_x_classifier.sh limliability
run_train_x_classifier.sh nonsolicit
run_train_x_classifier.sh party
run_train_x_classifier.sh preamble
run_train_x_classifier.sh renewal
run_train_x_classifier.sh sublicense
run_train_x_classifier.sh survival
run_train_x_classifier.sh term
run_train_x_classifier.sh termination
