#!/bin/sh
cd  /var/www/ebrevia-corenlp
java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -serverProperties StanfordCoreNLP.properties -port 9500 -status_port 9600 -timeout 600000 -quiet >> /var/log/ebrevia/corenlp.log 2>&1
