#!/bin/sh

echo "Awakening contract robot..."

cd /var/www/ebrevia-python

# https://github.com/scikit-learn/scikit-learn/issues/5115,
# https://github.com/joblib/joblib/blob/master/doc/parallel.rst#bad-interaction-of-multiprocessing-and-third-party-libraries
export JOBLIB_START_METHOD="forkserver"
exec gunicorn -b 0.0.0.0:8000 --timeout 21600 --workers 4 --preload app:app >> /var/log/ebrevia/gunicorn.log 2>&1
