extractor:
  image: 'mundtcake/ebrevia_onprem'
  environment:
    - TOMCAT_XMX=2g
    - OCR_SERVER_URL=http://ocrrecognitionserve-env.us-east-1.elasticbeanstalk.com/Recognition4WS/RSSoapService.asmx?WSDL
    - ONPREM=1
  ports:
    - '80:80'
  volumes:
    - '~/docker_eb_files:/eb_files'

